using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace SimpleStudentApi.Models;

/// <summary>A student stored in the SQL Server table <c>Students</c>.</summary>
/// <remarks>
/// The attributes below are part of the API contract: Swagger copies them into swagger.json
/// (required, maxLength, format: email, minimum/maximum, readOnly). Clients in any language
/// can read these rules – the PHP frontend builds its form fields from them.
/// </remarks>
public class Student
{
    /// <summary>Database ID (generated by SQL Server; ignored when creating).</summary>
    /// <example>1</example>
    [ReadOnly(true)]
    public int Id { get; set; }

    /// <summary>First name.</summary>
    /// <example>Jonas</example>
    [Required, StringLength(100)]
    public string FirstName { get; set; } = string.Empty;

    /// <summary>Last name.</summary>
    /// <example>Jonaitis</example>
    [Required, StringLength(100)]
    public string LastName { get; set; } = string.Empty;

    /// <summary>University email address.</summary>
    /// <example>jonas@university.lt</example>
    [Required, EmailAddress, StringLength(200)]
    public string Email { get; set; } = string.Empty;

    /// <summary>Study program, e.g. Computer Science.</summary>
    /// <example>Computer Science</example>
    [Required, StringLength(100)]
    public string StudyProgram { get; set; } = string.Empty;

    /// <summary>Year the student started studying (2000–2100).</summary>
    /// <example>2024</example>
    [Range(2000, 2100)]
    public int EnrollmentYear { get; set; }
}
