namespace SimpleStudentApi.Models;

/// <summary>A student stored in the SQL Server table <c>Students</c>.</summary>
public class Student
{
    /// <summary>Database ID (generated by SQL Server; ignored when creating).</summary>
    /// <example>1</example>
    public int Id { get; set; }

    /// <example>Jonas</example>
    public string FirstName { get; set; } = string.Empty;

    /// <example>Jonaitis</example>
    public string LastName { get; set; } = string.Empty;

    /// <example>jonas@university.lt</example>
    public string Email { get; set; } = string.Empty;

    /// <example>Computer Science</example>
    public string StudyProgram { get; set; } = string.Empty;

    /// <summary>Year the student started studying (2000–2100).</summary>
    /// <example>2024</example>
    public int EnrollmentYear { get; set; }
}
