<?php /** @var array $fields @var array $values @var array $errors @var string $action */ ?>
<form method="post" action="?page=<?= $action === 'update' ? 'edit' : 'create' ?>&id=<?= (int)$id ?>">
    <input type="hidden" name="action" value="<?= h($action) ?>">
    <?php foreach ($fields as $name => $f): ?>
        <?php if ($f['readOnly']) continue; /* e.g. id – generated by the database */ ?>
        <?= Form::input($name, $f, $values[$name] ?? null, $errors[$name] ?? []) ?>
    <?php endforeach; ?>
    <button type="submit" class="btn btn-create"><?= $action === 'update' ? 'Update Student' : 'Save Student' ?></button>
    <a class="cancel" href="?page=students">Cancel</a>
    <label class="novalidate"><input type="checkbox" onchange="this.form.noValidate = this.checked"> skip browser validation (to see the API's 400 response)</label>
</form>
